package it.grational.lemap

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 09-02-2018 10.06
 */
class FuzzyMapUSpec extends Specification {

	def "Should match the correct key based on the strings' similarity measure"() {
		setup:
			def simap = new FuzzyMap()
		and:
			simap << [
				ciao: 1,
				miao: 2,
				bau:  3
			]

		expect:
			simap.get(key) == expectedValue

		where:
			key    || expectedValue
			// exact matches
			'ciao' || 1
			'miao' || 2
			'bau'  || 3
			// similarity matches
			'ciai' || 1
			'zau'  || 3
	}

}
