package it.grational.lemap

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 09-02-2018 10.06
 */
class SimilarityMapSpec extends Specification {
	def "someSimilarityMapMethod returns true"() {
		setup:
			SimilarityMap lib = new SimilarityMap()
		when:
			Boolean result = lib.someSimilarityMapMethod()
		then:
			result == true
	}
}
