package it.grational.lemap

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author d7392
 * @date 09-02-2018 10.06
 */
@Slf4j
class SimilarityMap {
	/**
	 * This method returns always true.
	 */
	Boolean someSimilarityMapMethod() {
		true
	}
}
